---
# tasks file for jamie.create-ec2-instance
- name: Create an ec2 instance
  ec2:
    key_name: "{{ keypair }}"
    group_id: "{{ aws_security_group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    wait: yes
    region: "{{ aws_vpc_region }}"
    exact_count: "{{ instance_count }}"
    instance_tags:
      Name: "{{ aws_instance_name_tag }}"
      webtype: "{{ aws_instance_webtype_tag }}"
    count_tag:
      Name: "{{ aws_instance_name_tag }}"
      webtype: "{{ aws_instance_webtype_tag }}"
    vpc_subnet_id: "{{ target_vpc_subnet_id }}"
    assign_public_ip: "{{ aws_assign_public_ip }}"

  register: ec2
#- name: Return Value
#  debug: var=ec2.tagged_instances

- name: Return Value
  vars:
    msg: |
         Your instance in now available

         ssh -i {{ aws_key_pair }}.pem ec2-user@{{ item.public_dns_name }}

  debug:
    msg: "{{ msg.split('\n') }}"
  with_items: "{{ ec2.tagged_instances }}"

- meta: refresh_inventory

- name: Wait for the instances to boot by checking the ssh port
  wait_for: host={{ item.public_ip }} port=22 delay=1 timeout=320 state=started
  with_items: "{{ ec2.tagged_instances }}"

